// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface CTHelpers$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "CTHelpers";
  readonly sourceName: "contracts/CTHelpers.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220c789673d66f36448d7b73afc5a65c0714d91d9f1eed7ef6d0dd59852d1a8473164736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220c789673d66f36448d7b73afc5a65c0714d91d9f1eed7ef6d0dd59852d1a8473164736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/CTHelpers.sol";
  readonly buildInfoId: "solc-0_8_30-ffd34bdb928c85e939f7457114f12cb3671a4822";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["CTHelpers"]: CTHelpers$Type;
    ["contracts/CTHelpers.sol:CTHelpers"]: CTHelpers$Type;
  }
}