// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ABDKMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ABDKMath";
  readonly sourceName: "contracts/ABDKMath64x64.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220567225403b4b9ccaca83f7574cf3674e22a37b303cfe322cebc98efda38b397664736f6c634300081e0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220567225403b4b9ccaca83f7574cf3674e22a37b303cfe322cebc98efda38b397664736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ABDKMath64x64.sol";
  readonly buildInfoId: "solc-0_8_30-1a0bc46de25f36b3bfc8c67e6a4245f84569c46a";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ABDKMath"]: ABDKMath$Type;
    ["contracts/ABDKMath64x64.sol:ABDKMath"]: ABDKMath$Type;
  }
}